import io
import pymupdf
from typing import List, Dict, Any


class PDFDraftGenerator:
    """
    Generates downloadable PDF completion drafts for forms using PyMuPDF.
    Prominently banners the document with 'Draft — Review Before Use'.
    """

    def generate_form_draft(
        self,
        form_name: str,
        form_id: str,
        fields: List[Dict[str, Any]],
        checklist: List[str],
    ) -> bytes:
        doc = pymupdf.open()
        page = doc.new_page(width=595, height=842)  # Standard A4 (points)

        # Background header banner (Paper Canvas / Guidance Green theme)
        header_rect = pymupdf.Rect(36, 36, 559, 100)
        page.draw_rect(header_rect, color=(0.18, 0.42, 0.34), fill=(0.92, 0.95, 0.93))

        # Header Title
        page.insert_text(
            pymupdf.Point(48, 62),
            "EASYPAPER — FORM READINESS PLAN",
            fontsize=12,
            fontname="helv",
            color=(0.18, 0.42, 0.34),
        )
        page.insert_text(
            pymupdf.Point(48, 84),
            f"Form: {form_name}",
            fontsize=14,
            fontname="helv",
            color=(0.12, 0.14, 0.12),
        )

        # Draft Watermark Notice
        notice_rect = pymupdf.Rect(36, 110, 559, 134)
        page.draw_rect(notice_rect, color=(0.65, 0.38, 0.10), fill=(0.98, 0.95, 0.92))
        page.insert_text(
            pymupdf.Point(48, 126),
            "DRAFT FOR GUIDANCE ONLY — VERIFY ALL VALUES WITH OFFICIAL PORTAL BEFORE SUBMITTING",
            fontsize=8.5,
            fontname="helv",
            color=(0.65, 0.38, 0.10),
        )

        # Field-by-Field Sequential Table
        y_cursor = 160
        page.insert_text(
            pymupdf.Point(36, y_cursor),
            "FIELD-BY-FIELD COMPLETION VALUES (WRITE THESE IN THE FORM):",
            fontsize=10,
            fontname="helv",
            color=(0.18, 0.42, 0.34),
        )
        y_cursor += 20

        for idx, f in enumerate(fields, 1):
            if y_cursor > 740:
                page = doc.new_page(width=595, height=842)
                y_cursor = 50

            label = f.get("label_en", f"Field {idx}")
            val = str(f.get("proposed_value") or "[Needed - please fill manually]")
            source = f.get("source_description_en") or f.get("value_source", "manual")

            # Row background
            row_rect = pymupdf.Rect(36, y_cursor - 12, 559, y_cursor + 18)
            fill_color = (0.98, 0.97, 0.95) if idx % 2 == 0 else (1.0, 1.0, 1.0)
            page.draw_rect(row_rect, color=(0.90, 0.88, 0.84), fill=fill_color)

            # Field number and label
            page.insert_text(
                pymupdf.Point(44, y_cursor + 2),
                f"{idx}. {label}:",
                fontsize=9,
                fontname="helv",
                color=(0.36, 0.40, 0.32),
            )

            # Value
            page.insert_text(
                pymupdf.Point(230, y_cursor + 2),
                val[:45],
                fontsize=9.5,
                fontname="helv",
                color=(0.12, 0.14, 0.12),
            )

            # Source Tag
            page.insert_text(
                pymupdf.Point(440, y_cursor + 2),
                f"[{source[:18]}]",
                fontsize=7.5,
                fontname="helv",
                color=(0.18, 0.42, 0.34),
            )

            y_cursor += 34

        # Pre-submission Checklist Section
        if y_cursor > 700:
            page = doc.new_page(width=595, height=842)
            y_cursor = 50

        y_cursor += 15
        page.insert_text(
            pymupdf.Point(36, y_cursor),
            "SUBMISSION CHECKLIST & REQUIRED ATTACHMENTS:",
            fontsize=10,
            fontname="helv",
            color=(0.18, 0.42, 0.34),
        )
        y_cursor += 18

        for item in checklist:
            if y_cursor > 780:
                page = doc.new_page(width=595, height=842)
                y_cursor = 50
            page.insert_text(
                pymupdf.Point(48, y_cursor),
                f"[  ]  {item}",
                fontsize=8.5,
                fontname="helv",
                color=(0.20, 0.22, 0.20),
            )
            y_cursor += 16

        # Footer
        page.insert_text(
            pymupdf.Point(36, 810),
            "Generated by Paperwork & Access | Independent public guidance tool | Synthetic Demo",
            fontsize=7.5,
            fontname="helv",
            color=(0.50, 0.50, 0.50),
        )

        pdf_bytes = doc.tobytes()
        doc.close()
        return pdf_bytes


pdf_draft_generator = PDFDraftGenerator()
